/*
 * Copyright (c) 2008, 2019 Emmanuel Dupuy.
 * This project is distributed under the GPLv3 license.
 * This is a Copyleft license that gives the user the right to use,
 * copy and modify the code freely for non-commercial purposes.
 */

package org.jd.core.v1.service.converter.classfiletojavasyntax.util;

import org.jd.core.v1.model.classfile.ConstantPool;
import org.jd.core.v1.model.classfile.Method;
import org.jd.core.v1.model.classfile.attribute.AttributeBootstrapMethods;
import org.jd.core.v1.model.classfile.attribute.AttributeCode;
import org.jd.core.v1.model.classfile.attribute.AttributeRecord;
import org.jd.core.v1.model.classfile.attribute.BootstrapMethod;
import org.jd.core.v1.model.classfile.constant.ConstantMemberRef;
import org.jd.core.v1.model.classfile.constant.ConstantMethodHandle;
import org.jd.core.v1.model.javasyntax.declaration.*;
import org.jd.core.v1.model.javasyntax.expression.Expression;
import org.jd.core.v1.model.javasyntax.statement.BaseStatement;
import org.jd.core.v1.model.javasyntax.statement.Statement;
import org.jd.core.v1.model.javasyntax.statement.Statements;
import org.jd.core.v1.service.converter.classfiletojavasyntax.model.javasyntax.declaration.*;
import org.jd.core.v1.service.converter.classfiletojavasyntax.model.javasyntax.expression.ClassFileLocalVariableReferenceExpression;
import org.jd.core.v1.service.converter.classfiletojavasyntax.model.localvariable.AbstractLocalVariable;
import org.jd.core.v1.util.DefaultList;

import java.util.Iterator;
import java.util.List;

import static org.jd.core.v1.model.javasyntax.declaration.Declaration.*;

/**
 * Records (Java 16+): hide the members generated by javac.
 * <ul>
 *     <li>the private final fields of the components,</li>
 *     <li>the accessors returning these fields,</li>
 *     <li>toString(), hashCode() and equals(Object) implemented with java.lang.runtime.ObjectMethods,</li>
 *     <li>the field assignments of the canonical constructor, printed as a compact constructor (or removed if
 *     empty).</li>
 * </ul>
 */
public class RecordDeclarationUtil {
    protected static final String OBJECT_METHODS = "java/lang/runtime/ObjectMethods";

    public static void update(ClassDeclaration declaration, ClassFileBodyDeclaration bodyDeclaration) {
        AttributeRecord attributeRecord = bodyDeclaration.getClassFile().getAttribute("Record");

        if (attributeRecord == null) {
            return;
        }

        org.jd.core.v1.model.classfile.attribute.RecordComponent[] components = attributeRecord.getComponents();
        int length = components.length;
        String[] names = new String[length];
        StringBuilder canonicalDescriptor = new StringBuilder("(");

        for (int i=0; i<length; i++) {
            names[i] = components[i].getName();
            canonicalDescriptor.append(components[i].getDescriptor());
        }

        canonicalDescriptor.append(")V");

        // Records are implicitly final, and static when nested
        if (declaration instanceof TypeDeclaration) {
            ((TypeDeclaration)declaration).setFlags(declaration.getFlags() & ~(FLAG_FINAL|FLAG_STATIC));
        }

        removeComponentFields(bodyDeclaration, names);

        List<ClassFileConstructorOrMethodDeclaration> methods = bodyDeclaration.getMethodDeclarations();
        AttributeBootstrapMethods attributeBootstrapMethods = bodyDeclaration.getClassFile().getAttribute("BootstrapMethods");

        if (methods == null) {
            return;
        }

        Iterator<ClassFileConstructorOrMethodDeclaration> iterator = methods.iterator();

        while (iterator.hasNext()) {
            ClassFileConstructorOrMethodDeclaration comd = iterator.next();
            Method method = comd.getMethod();

            if (comd instanceof ClassFileConstructorDeclaration) {
                if (canonicalDescriptor.toString().equals(method.getDescriptor()) &&
                        updateCanonicalConstructor(declaration, (ClassFileConstructorDeclaration)comd, names)) {
                    iterator.remove();
                }
            } else if (comd instanceof ClassFileMethodDeclaration) {
                if (isObjectMethod(method, attributeBootstrapMethods) || isAccessor((ClassFileMethodDeclaration)comd, components)) {
                    iterator.remove();
                }
            }
        }
    }

    protected static void removeComponentFields(ClassFileBodyDeclaration bodyDeclaration, String[] names) {
        List<ClassFileFieldDeclaration> fields = bodyDeclaration.getFieldDeclarations();

        if (fields == null) {
            return;
        }

        Iterator<ClassFileFieldDeclaration> iterator = fields.iterator();

        while (iterator.hasNext()) {
            ClassFileFieldDeclaration field = iterator.next();

            if ((field.getFlags() & FLAG_STATIC) != 0) {
                continue;
            }

            BaseFieldDeclarator declarators = field.getFieldDeclarators();

            if (declarators.isList()) {
                DefaultList<FieldDeclarator> list = declarators.getList();
                list.removeIf(fd -> contains(names, fd.getName()));

                if (list.isEmpty()) {
                    iterator.remove();
                }
            } else if (contains(names, declarators.getFirst().getName())) {
                iterator.remove();
            }
        }
    }

    /**
     * @return true if the constructor can be removed
     */
    protected static boolean updateCanonicalConstructor(ClassDeclaration declaration, ClassFileConstructorDeclaration constructor, String[] names) {
        BaseFormalParameter formalParameters = constructor.getFormalParameters();
        int length = names.length;
        AbstractLocalVariable[] parameters = new AbstractLocalVariable[length];

        if (length > 0) {
            if ((formalParameters == null) || (formalParameters.size() != length)) {
                return false;
            }

            // The parameters of the canonical constructor have the names of the components
            int i = 0;
            for (FormalParameter formalParameter : formalParameters) {
                if (!(formalParameter instanceof ClassFileFormalParameter)) {
                    return false;
                }
                ClassFileFormalParameter cffp = (ClassFileFormalParameter)formalParameter;
                parameters[i] = cffp.getLocalVariable();
                cffp.setName(names[i]);
                i++;
            }

            // Varargs
            if ((constructor.getFlags() & FLAG_VARARGS) != 0) {
                BaseFormalParameter components = declaration.getRecordComponents();
                FormalParameter last = components.getLast();
                FormalParameter varargs = new FormalParameter(last.getAnnotationReferences(), last.getType(), true, last.getName());

                if (components.isList()) {
                    DefaultList<FormalParameter> list = components.getList();
                    list.set(list.size()-1, varargs);
                } else {
                    declaration.setRecordComponents(varargs);
                }
            }
        }

        BaseStatement baseStatements = constructor.getStatements();

        if ((baseStatements == null) || !baseStatements.isStatements()) {
            return false;
        }

        Statements statements = (Statements)baseStatements;
        int size = statements.size();

        if (size < length) {
            return false;
        }

        // Search the trailing assignments "this.<component> = <parameter>;"
        for (int i=0; i<length; i++) {
            Statement statement = statements.get(size - length + i);
            Expression expression = statement.getExpression();

            if (!statement.isExpressionStatement() || !expression.isBinaryOperatorExpression() || !"=".equals(expression.getOperator())) {
                return false;
            }

            Expression left = expression.getLeftExpression();
            Expression right = expression.getRightExpression();

            if (!left.isFieldReferenceExpression() || !names[i].equals(left.getName()) || (left.getExpression() == null) || !left.getExpression().isThisExpression()) {
                return false;
            }

            if (!(right instanceof ClassFileLocalVariableReferenceExpression) || (((ClassFileLocalVariableReferenceExpression)right).getLocalVariable() != parameters[i])) {
                return false;
            }
        }

        statements.subList(size - length, size).clear();

        int accessFlags = FLAG_PUBLIC|FLAG_PROTECTED|FLAG_PRIVATE;

        if (statements.isEmpty() && ((constructor.getFlags() & accessFlags) == (declaration.getFlags() & accessFlags)) &&
                (constructor.getAnnotationReferences() == null) && (constructor.getExceptionTypes() == null)) {
            // Implicit canonical constructor
            return true;
        }

        constructor.setCompactCanonical(true);
        return false;
    }

    protected static boolean isAccessor(ClassFileMethodDeclaration method, org.jd.core.v1.model.classfile.attribute.RecordComponent[] components) {
        if ((method.getFlags() & FLAG_STATIC) != 0) {
            return false;
        }

        String name = method.getName();
        String descriptor = method.getDescriptor();

        for (org.jd.core.v1.model.classfile.attribute.RecordComponent component : components) {
            if (component.getName().equals(name) && ("()" + component.getDescriptor()).equals(descriptor)) {
                BaseStatement statements = method.getStatements();

                if ((statements != null) && (statements.size() == 1) && statements.getFirst().isReturnExpressionStatement()) {
                    Expression expression = statements.getFirst().getExpression();

                    return expression.isFieldReferenceExpression() && name.equals(expression.getName()) &&
                            (expression.getExpression() != null) && expression.getExpression().isThisExpression();
                }

                return false;
            }
        }

        return false;
    }

    /**
     * @return true if the method calls java.lang.runtime.ObjectMethods.bootstrap: "toString()", "hashCode()" or
     *         "equals(Object)" generated by javac
     */
    protected static boolean isObjectMethod(Method method, AttributeBootstrapMethods attributeBootstrapMethods) {
        String name = method.getName();
        String descriptor = method.getDescriptor();

        if (!("toString".equals(name) && "()Ljava/lang/String;".equals(descriptor)) &&
                !("hashCode".equals(name) && "()I".equals(descriptor)) &&
                !("equals".equals(name) && "(Ljava/lang/Object;)Z".equals(descriptor))) {
            return false;
        }

        AttributeCode attributeCode = method.getAttribute("Code");

        if (attributeCode == null) {
            return false;
        }

        ConstantPool constants = method.getConstants();
        byte[] code = attributeCode.getCode();

        for (int offset = 0; offset < code.length; offset = ByteCodeUtil.getNextInstructionOffset(code, offset)) {
            if ((code[offset] & 255) == 186) { // INVOKEDYNAMIC
                ConstantMemberRef indy = constants.getConstant(((code[offset+1] & 255) << 8) | (code[offset+2] & 255));
                return OBJECT_METHODS.equals(getBootstrapClassName(attributeBootstrapMethods, constants, indy.getClassIndex()));
            }
        }

        return false;
    }

    protected static String getBootstrapClassName(AttributeBootstrapMethods attributeBootstrapMethods, ConstantPool constants, int bootstrapMethodIndex) {
        if ((attributeBootstrapMethods == null) || (bootstrapMethodIndex >= attributeBootstrapMethods.getBootstrapMethods().length)) {
            return null;
        }

        BootstrapMethod bootstrapMethod = attributeBootstrapMethods.getBootstrapMethods()[bootstrapMethodIndex];
        ConstantMethodHandle constantMethodHandle = constants.getConstant(bootstrapMethod.getBootstrapMethodRef());
        ConstantMemberRef constantMemberRef = constants.getConstant(constantMethodHandle.getReferenceIndex());

        return constants.getConstantTypeName(constantMemberRef.getClassIndex());
    }

    protected static boolean contains(String[] names, String name) {
        for (String n : names) {
            if (n.equals(name)) {
                return true;
            }
        }
        return false;
    }
}
